- name: Install Composer
  sudo: yes
  get_url: url=https://getcomposer.org/download/1.0.0-alpha11/composer.phar dest=/usr/bin/composer owner={{dvm_user}} group=apache mode=755

- name: Install PHPUnit
  sudo: yes
  get_url: url=https://phar.phpunit.de/phpunit-5.0.9.phar dest=/usr/local/bin/phpunit mode=755

- name: Install Composer For Project
  copy: src=../files/composer.json dest=/usr/local/composer.json owner=root mode=777

- name: Install PHPCodeSniffer
  composer:
    command: "global require squizlabs/php_codesniffer=2.3.2"
    working_dir: "/usr/local"
    no_dev: no
    optimize_autoloader: no

- name: Install PHPCompatibility
  composer:
    command: "global require wimg/php-compatibility=dev-master"
    working_dir: "/usr/local"
    no_dev: no
    optimize_autoloader: no

- name: Install simplyadmire/composer-plugins
  composer:
    command: "require simplyadmire/composer-plugins=@dev"
    working_dir: "/usr/local"
    no_dev: no
    optimize_autoloader: no

- name: Run composer install
  composer:
    command: "install"
    working_dir: "/usr/local"

- name: Link phpcs to /usr/local/bin/phpcs
  file: state=link src="/usr/local/vendor/bin/phpcs" dest="/usr/local/bin/phpcs" follow=yes

- name: Link PHPCompatibility into php_codesniffer standards.
  file: state=link src="/usr/local/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PhpCompatibility" dest="/usr/local/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility" follow=yes
