- set_fact:
    configuration_files:
      - "01standard"
      - "charset"
      - "fileperms"
      - "localized-error-pages"
      - "monitoring"
      - "other-vhosts-access-log"
      - "security"

- name: Create /usr/local/apache/logs
  file: dest=/usr/local/apache/logs recurse=yes state=directory owner=www-data group=apache mode=755

- name: Copy conf.d files
  template: src="conf.d/{{item}}.tpl" dest="/etc/apache2/conf-available/{{item}}.conf"
  with_items: configuration_files

- name: Enable conf.d files
  command: a2enconf {{item}} creates="/etc/apache2/conf-enabled/{{item}}.conf"
  with_items: configuration_files