---
- name: Install Apache Bin
  apt: name=apache2-bin state=present force=yes

- name: Install Apache
  apt: name=apache2-data state=present force=yes

- name: Install Apache
  apt: name=apache2 state=present force=yes

- name: Install Apache2 Utils
  apt: name=apache2-utils state=present force=yes

- name: Enable SSL Mod
  sudo: yes
  command: a2enmod ssl
  notify: restart apache2

- name: Enable Mod Headers
  sudo: yes
  command: a2enmod headers
  notify: restart apache2

- name: Create apache group
  group: name=apache state=present

- name: Add www-data to apache group
  user: name=www-data groups=www-data append=yes
