---
- name: Install launchpad
  apt_repository: repo='deb http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu trusty main'
  when: php.ppa is defined

- name: Install launchpad sources
  apt_repository: repo='deb-src http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu trusty main'
  when: php.ppa is defined

- name: Install ondrej/ppa
  apt_repository: repo='ppa:ondrej/{{php.ppa}}'
  when: php.ppa is defined

- name: Update apt
  sudo: yes
  apt: update_cache=yes cache_valid_time=86400

- name: Install php5
  sudo: yes
  apt: pkg=php5 state=present force=yes

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=present force=yes
  with_items: php.packages
  when: php.packages is defined

- include: pecl.yml
