- name: Install
  apt: pkg=php5-dev state=present force=yes
  when: php.pecl_packages is defined

- name: Install libxml2
  apt: pkg=libxml2-dev state=present force=yes

- name: Install php5 gd
  apt: pkg=php5-gd state=present force=yes

- name: Install Package
  shell: echo "\n\n\n\n\n\n\n\n\n" | pecl install {{ item }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  with_items: php.pecl_packages_versions
  when: php.pecl_packages_versions is defined

- name: Enable extension
  shell: php5enmod {{ item }} creates=/etc/php5/apache2/conf.d/20-{{ item }}.ini
  with_items: php.pecl_packages
  when: php.pecl_packages is defined
